name: lyric-aligner
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchaudio
  - cpuonly
  - pip
  - pip:
    - librosa
    - soundfile
    - numpy
    - scipy
    - cmudict